version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: share_storage_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret_password123
      POSTGRES_DB: storage_management
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: